create table public.categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null,
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;

create table public.stories (
  summary text null,
  accuracy_assessment text null,
  accuracy_score bigint null,
  propaganda_indicators text null,
  propaganda_score bigint null,
  author_sources text null,
  author_source_bias text null,
  ai_sources text null,
  overall_metrics text null,
  id bigint generated by default as identity not null,
  category_id bigint null,
  category text null
) TABLESPACE pg_default;